### ISSUE TITLE
Choose what relationship between files dynamically

### ISSUE THREAD

**Issue by HunteRoi** [Arsero/docusaurus-graph#2]
Hey @Arsero !

I have been playing with your plugin and I find it quite useful! Although I think you might want to add a system for dynamic search of the relationships between files instead of manually setting them up.

I ended up with having a few proposals for you.

## 1st suggestion 

Use the `tags` header information on each blog post/docs page to create the relationships between files (sources : https://docusaurus.io/docs/create-doc#doc-tags and https://docusaurus.io/docs/blog). I have a page to list tags I used on my website (available [here](https://tinaeldevresse.eu/fr/blog/tags)) which means there might be an API available in docusaurus to have the list of tags for the website as well as parse them from any file.

## 2nd suggestion

Shift the plugin on a more open stance by allowing users to choose what kind of relationships they want based on functions you write and export from your own package.

Let me provide you with an example.

```ts filename="docusaurus.config.ts"
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

import { basedOnTags, basedOnParentFolder, basedOnMentions } from 'docusaurus-graph';

const config: Config = {
   // ...
   plugins: [
       [
           "docusaurus-graph",
           {
               path: "docs",
               basedOn: basedOnParentFolder
           }
       ]
   ]
   // ...
};

export default config;
```

As you probably understand, you could expand it with default functions you provide but also allow other people to come up with their own relationships function!

**Comment by Arsero** [comment]
Hi HunteRoi,

Thank you for reporting this issue! The problem has been resolved in the latest release, version 2.0.0. 🎉 Please update to this version and let me know if you encounter any further issues.

Feel free to reopen this issue or create a new one if needed. Thanks for your support!

Best regards,
Arsero

**Comment by johnmcase** [comment]
@Arsero How has this issue been resolved?  I still don't see anyway for the plugin to discover relationships between files other than manually declaring relationships via the `sources` and `references` tags
